### ISSUE TITLE
Frontal retreat

### ISSUE THREAD

**Issue by mankoff** [mankoff/cryo-misc#11]
https://github.com/mankoff/sankey/blob/8476eb79dadb205b149e425743b99050876f10a1/dat/aq_baseline.csv#L9

**Comment by chadagreene** [comment]
[greene_Supplementary_Table_1.xlsx](https://github.com/user-attachments/files/15598602/greene_Supplementary_Table_1.xlsx)

I think the data in the attached spreadsheet from [Greene et al., 2022 ](https://doi.org/10.1038/s41586-022-05037-w) is everything needed for ice-shelf mass-change resulting from frontal advance/retreat, so in Excel `=BI189-O189` gives Antarctica's net retreat from 1997 to 2021. Change the column to adjust the time period.
