### ISSUE TITLE
Frontal advance in Greenland

### ISSUE THREAD

**Issue by mankoff** [mankoff/cryo-misc#19]
Hi @willkochtitzky

As of 9e2b09ba18ff84efebdac11bffd33f64ff5da2bb I now have frontal advance AND frontal retreat for Antarctica and show both in all figures (no longer net frontal change). Do you have frontal advance for Greenland?

Your 2022 GRL paper mentions 2.5 % advanced, and gives numbers, but dimensions are length not mass.

Your 2022 nature paper says

> For the entire Northern Hemisphere, the total terminus mass loss of 11.57 ± 3.81 Gt a−1 during 2010–2020 consisted of 2.98 ± 0.70 Gt a−1 of terminus advance and 14.54 ± 5.97 Gt a−1 of terminus retreat

I could use that, but I thought net retreat was 50 Gt/year - what I currently use in Greenland for the graphic linked above. 50 Gt/yr comes from your 2023 paper abstract, `510.2 ± 18.6 Gt a−1 for 2010–2020`.

**Comment by mankoff** [comment]
Note that if these numbers are not easily available, I think I can probably get them from the Greene 2024 dataset.

**Comment by mankoff** [comment]
I explored this with the Greene 2022 dataset and there does not appear to be any significant advance. I think it's fine to show Greenland as retreat-only.

**Comment by willkochtitzky** [comment]
Hi Ken, sorry I just never replied to this. I just looked at my data. For 2000-2010 Greenland had 0.21 ± 0.10 GT/yr of advance and 0.21 ± 0.16 Gt/yr for 2010-2020. I agree these are so small they are not worth showing, but you have that data now if you want it.
